---
- name: H2 INVENT | Check for composer.phar
  stat: path={{symfony_composer_path}}
  register: composer_file

- name: H2 INVENT | Run composer self-update
  shell: "{{symfony_composer_path}} selfupdate --no-interaction"
  when: composer_file.stat.exists and symfony_composer_self_update|bool
  register: composer_self_update_result
  changed_when: composer_self_update_result.stderr is search('Updating')

- name: H2 INVENT | Run composer install.
  command: "{{symfony_php_path}} {{symfony_composer_path}} install"