---
- name: Create Backup Directory
  file:
    path: "/tml/backup/{{ path }}"
    state: directory

- name: "Backup {{ path }} DB"
  mysql_db:
    name: "{{ symfony_doctrine_dump_db.name }}"
    state: "dump"
    target: "/tml/backup/{{ path }}/migration.sql"
    login_host: "10.10.1.80"
    login_user: "{{ symfony_doctrine_dump_db.user }}"
    login_password: "{{ symfony_doctrine_dump_db.password }}"

- name: H2 INVENT | DOCTRINE | Run Doctrine migrations
  shell: chdir={{ansistrano_release_path.stdout}}
    SYMFONY_ENV={{symfony_env}} APP_ENV={{symfony_env}} {{symfony_php_path}} {{symfony_console_path}} doctrine:migrations:migrate --no-interaction {{symfony_doctrine_options}}
  run_once: '{{ symfony_run_doctrine_migration_once | bool }}'
